### ISSUE TITLE
Why don't just give us more explanatory instructions 

### ISSUE THREAD

**Issue by abdulbadii** [mdwhatcott/gofish#1]
Why don't just give us more explanatory instructions on how to compile it on linux and mingw system.
Because I tried it in Mingw64 but got:
go build ./...
go: cannot find GOROOT directory: F:\msys64\mingw64\lib\go
make: *** [Makefile:4: test] Error 2

Thanks in advance!

**Comment by mdwhatcott** [comment]
I never finished the engine. But you're welcome to fork the repo and continue on. ;)
